// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YummyFood.Core.Entities
{
    public partial class ImageDetail
    {
        public ImageDetail()
        {
            Products = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public string ImagePath { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? Guid { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}