// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YummyFood.Core.Entities
{
    public partial class Product
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public bool? Enabled { get; set; }
        public bool? Deleted { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ProductName { get; set; }
        public int? ProductCode { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? ImageId { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }

        public virtual ImageDetail Image { get; set; }
    }
}