// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YummyFood.Core.Entities
{
    public partial class SignInLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Ipaddress { get; set; }
        public DateTime? LoginTime { get; set; }
        public DateTime? LogoutTime { get; set; }
        public string BrowserInfo { get; set; }

        public virtual User User { get; set; }
    }
}